version: '3.8'

services:
  # Spring Boot service
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: urlshortner-app:latest
    ports:
      - "8090:8090"  # Mapping the Spring Boot app to port 8090 on the host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demodb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Harsh@1558
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_SHOW-SQL: true
    depends_on:
      - mysql

  # MySQL service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Harsh@1558
      MYSQL_DATABASE: demodb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
